[package]
name = "zero-cve-liquidity-engine"
version = "1.0.0"
edition = "2021"

[dependencies]
# Solana ecosystem (pure Rust, no JavaScript)
solana-client = "1.18"
solana-sdk = "1.18"
solana-program = "1.18"
solana-transaction-status = "1.18"

# HTTP client (pure Rust, replaces axios/node-fetch)
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Cryptography (pure Rust)
aes-gcm = "0.10"
rand = "0.8"
sha2 = "0.10"
hmac = "0.12"
pbkdf2 = "0.12"
base64 = "0.21"
hex = "0.4"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
log = "0.4"
env_logger = "0.10"

# Data structures
rust_decimal = { version = "1.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# WASM support (for frontend integration)
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }

[dev-dependencies]
tokio-test = "0.4"
