[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gaming_rewards_program = "GkdgN6BBTURDsXeojvvz13VN5T43zaKRrf7XMJHjPNze"

[programs.devnet]
gaming_rewards_program = "GkdgN6BBTURDsXeojvvz13VN5T43zaKRrf7XMJHjPNze"

[programs.mainnet]
gaming_rewards_program = "GkdgN6BBTURDsXeojvvz13VN5T43zaKRrf7XMJHjPNze"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"
verify = "anchor verify"
